/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eliamercatanti.guesthousebooking.app;

public class App {

	private static final String HELLO_WORLD = "Hello World!";

	public String getGreeting() {
		return HELLO_WORLD;
	}

	public static void main(String[] args) {
		System.out.println(new App().getGreeting());
	}
}
