/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eliamercatanti.guesthousebooking.app.swing;

import com.eliamercatanti.guesthousebooking.view.swing.GuesthouseSwingView;

public class GuesthouseSwingApp {

	public static void main(String[] args) {
		GuesthouseSwingView frame = new GuesthouseSwingView();
		frame.setVisible(true);
	}
}
