# This workflow will build a Java project with Gradle in Windows and macOS only on Pull Requests
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle in Windows and macOS only on PRs

on:
   pull_request:
   
jobs:
   build:
      runs-on: ${{ matrix.os }}
      strategy:
         matrix:
            os: [windows-2019, macos-10.15]
      
      steps:
      -  uses: actions/checkout@v2
      -  name: Set up JDK 11 on ${{ matrix.os }}
         uses: actions/setup-java@v2
         with:
            java-version: 11
            distribution: 'adopt'
      -  name: Cache Gradle packages
         uses: actions/cache@v2
         with:
            path: |
               ~/.gradle/caches
               ~/.gradle/wrapper
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/*.yml') }}
            restore-keys: |
               $(( runner.os ))-gradle-
      -  name: Grant execute permission for gradlew
         run: chmod +x gradlew
      -  name: Build with Gradle
         run: ./gradlew build -i
      -  name: Archive JUnit Report
         uses: actions/upload-artifact@v2
         if: ${{ failure() }}
         with:
            name: junit-report-${{ matrix.os }}
            path: '**/build/reports/tests/test'
      -  name: Upload jar and fatjar as Artifacts
         uses: actions/upload-artifact@v2
         with:
            name: guesthouse-reservations-packages-${{ matrix.os }}
            path: '**/build/libs'
      -  name: Cleanup Gradle Cache
         run: |
           rm -Force ~/.gradle/caches/modules-2/modules-2.lock
           rm -Force ~/.gradle/caches/modules-2/gc.properties
         