# This workflow will build a Java project with Gradle in Linux
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle in Windows

on:
   push:
   pull_request:
   
jobs:
   build:
      runs-on: windows-2019
      env:
         DOCKER_HOST: tcp://localhost:2375
      
      steps:
      -  uses: actions/checkout@v2
         with:
            fetch-depth: 0
      -  name: Set up JDK 11
         uses: actions/setup-java@v2
         with:
            java-version: 11
            distribution: 'adopt'
      -  name: Cache Gradle and SonarQube Packages
         uses: actions/cache@v2
         with:
            path: |
               ~/.gradle/caches
               ~/.gradle/wrapper
               ~/.sonar/cache
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/*.yml') }}
            restore-keys: |
               $(( runner.os ))-gradle-
      -  name: Docker Configuration
         run: |
            sc config docker binpath="dockerd.exe --run-service -H tcp://localhost:2375"
      -  name: Docker Restart
         run: restart-service *docker*
      -  name: Grant Execute Permission for Gradlew
         run: chmod +x gradlew
      -  name: Build with Gradle
         env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         run: ./gradlew build jacocoTestReport coverallsJacoco pitest sonarqube -i
      -  name: Archive Unit Tests Report
         uses: actions/upload-artifact@v2
         if: ${{ failure() }}
         with:
            name: unit-tests-report
            path: '**/build/reports/tests/test'
      -  name: Archive Integration Tests Report
         uses: actions/upload-artifact@v2
         if: ${{ failure() }}
         with:
            name: integration-tests-report
            path: '**/build/reports/tests/integrationTest'
      -  name: Archive End to End Tests Report
         uses: actions/upload-artifact@v2
         if: ${{ failure() }}
         with:
            name: integration-tests-report
            path: '**/build/reports/tests/endToEndTest'
      -  name: Archive PIT Report
         uses: actions/upload-artifact@v2
         if: ${{ failure() }}
         with:
            name: pit-report
            path: '**/build/reports/pitest'
      -  name: Archive Jar and Fatjar
         uses: actions/upload-artifact@v2
         with:
            name: guesthouse-reservations-packages
            path: '**/build/libs'
            