# This workflow will build a Java project with Gradle in Linux
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle in Linux

on:
   push:
   pull_request:
   
jobs:
   build:
      runs-on: ubuntu-20.04
      
      steps:
      -  uses: actions/checkout@v2
         with:
            ref: ${{ github.event.pull_request.head.sha }}
      -  name: Set up JDK 11
         uses: actions/setup-java@v1
         with:
            java-version: 11
      -  name: Cache Gradle packages
         uses: actions/cache@v2
         with:
            path: |
               ~/.gradle/caches
               ~/.gradle/wrapper
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/*.yml') }}
            restore-keys: |
               $(( runner.os ))-gradle-
      -  name: Grant execute permission for gradlew
         run: chmod +x gradlew
      -  name: Build with Gradle
         env:
            COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
         run: ./gradlew build jacocoTestReport coverallsJacoco
      -  name: Archive JUnit Report
         uses: actions/upload-artifact@v2
         if: ${{ failure() }}
         with:
            name: junit-report
            path: '**/build/reports/tests/test'
      -  name: Upload jar and fatjar as Artifacts
         uses: actions/upload-artifact@v2
         with:
            name: guesthouse-reservations-packages
            path: '**/build/libs'
            