name: Java CI with Gradle in Linux On Pull Request

on:
   pull_request:
   
jobs:
   build:
      runs-on: ubuntu-20.04
      steps:
      -  uses: actions/checkout@v2
         with:
            fetch-depth: 0
      -  name: Set up JDK 11
         uses: actions/setup-java@v2
         with:
            java-version: 11
            distribution: 'adopt'
      -  name: Cache Gradle and SonarQube Packages
         uses: actions/cache@v2
         with:
            path: |
               ~/.gradle/caches
               ~/.gradle/wrapper
               ~/.sonar/cache
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/*.yml') }}
            restore-keys: |
               $(( runner.os ))-gradle-
      -  name: Grant Execute Permission for Gradlew
         run: chmod +x gradlew
      -  name: Build with Gradle
         env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         run: xvfb-run ./gradlew build -i
      -  name: Archive Unit Tests Report
         uses: actions/upload-artifact@v2
         if: ${{ failure() }}
         with:
            name: unit-tests-report
            path: '**/build/reports/tests/test'
      -  name: Archive Integration Tests Report
         uses: actions/upload-artifact@v2
         if: ${{ failure() }}
         with:
            name: integration-tests-report
            path: '**/build/reports/tests/integrationTest'
      -  name: Archive End to End Tests Report
         uses: actions/upload-artifact@v2
         if: ${{ failure() }}
         with:
            name: integration-tests-report
            path: '**/build/reports/tests/endToEndTest'
      -  name: Archive Jar and Fatjar
         uses: actions/upload-artifact@v2
         if: ${{ success() }}
         with:
            name: guesthouse-reservations-packages
            path: '**/build/libs'
         